name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04   # 明确使用 24.04，它自带 SDK
    env:
      # 使用镜像预置的 SDK，不再自己安装
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk/27.3.13750724  # 镜像已装 27.3
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install系统依赖
        run: 
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          pip install buildozer cython
          
      - name: Accept Android SDK licenses
        run: 
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses || true
          echo "y" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "build-tools;36.0.0"

      - name: Build APK
        run: 
          buildozer android debug --compressed

      - uses: actions/upload-artifact@v4
        with:
          name: RandomPicker-debug
          path: bin/RandomPicker-debug.apk